# Generated by Django 5.2.12 on 2026-03-06 13:05

import martor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=martor.models.MartorField(),
        ),
    ]
